### ISSUE TITLE
upgrade rn to v0.44

### ISSUE THREAD

**Issue by zhangwen9229** [gameboyVito/react-native-ultimate-listview#3]
hello,hello,anybody there?O(∩_∩)O哈哈~

ExceptionsManager.js:71 Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.  
Warning: View.AccessibilityTraits has been deprecated and will be removed in a future version of ReactNative. Use ViewAccessibility.AccessibilityTraits instead.
![96b51c20-421c-437e-92ab-5490c7d8bc0e](https://cloud.githubusercontent.com/assets/5137377/25799024/fc5b226c-3415-11e7-8a44-45b5968cbef8.png)

![75d6c14f-d44a-44a4-a596-77947e99f464](https://cloud.githubusercontent.com/assets/5137377/25799139/76c4dc6e-3416-11e7-9155-e482f7be10d5.png)

**Comment by gameboyVito** [comment]
Sorry, I was trying to integrate with `react-native-sglistview` to bring a better performance on memory control, but it seems like that package has too many bugs, so I reverted to the old one. I have updated my Example code and fixed a few bugs, you can update to `v2.0.9`, it should be fixed. 

Next step, I will open a dev branch to migrate the latest `FlatList`, so that it can bring a better performance without memory leaking.

**Comment by zhangwen9229** [comment]
OK，I will try new version 2.0.9. thank you.  Keep moving.

**Comment by gameboyVito** [comment]
I have published the latest 3.0.0 to support the awesome `FlatList`, if you are interested, feel free to try.

**Comment by zhangwen9229** [comment]
嗯，👌
